### ISSUE TITLE
ottenere autorizzazione da comunità OSM per l'uso di BikingImprover

### ISSUE THREAD

**Issue by napo** [DigitalCommonsLab/bikingImproving_day#12]
Copia/incolla della email di Francesco

----

Prima di avviare la sfida dovreste contattare la comunità di OSM della zona (https://wiki.openstreetmap.org/wiki/Import/Guidelines  Step 4 community buy ins).

La pagina wikipedia riguardante l'import della web app si trova sul link 
https://wiki.openstreetmap.org/wiki/Biking-Improver-Import

---

**Comment by silviarss** [comment]
La procedura di import è stata svolta, è possibile trovare la discussione al seguente link: 
[Discussione community italiana](https://community.openstreetmap.org/t/importing-data-bikingimprover/104275)
